#!perl

use strict;
use Getopt::Std;

# Usage: perl merge.pl [-d src] [-o output] [files ...]
# This program takes a list of games associated with particular generic
# tiles, stored in the files, and emits an updated version of the file
# src/18-gentl.ps.  The input lines are:
#		nnn: g, ...
# as generated by concord.pl.

my %gamelist;
my %opts;
$opts{d} = ".";
$opts{o} = "-";
getopts ('d:o:', \%opts);
open OUT, ">$opts{o}" or die "unable to open output file $opts{o}: $!\n";

while (<>) {
	chomp;
	my @f = split /:/;
	$f[1] =~ s/^\s*//;
	$gamelist{$f[0] + 0} = $f[1];
}
$gamelist{0} = "Special";

open GENTL, "<$opts{d}/18-gentl.ps"
    or die "Unable to open $opts{d}/18-gentl.ps: $!\n";
while (<GENTL>) {
	if (m!^/Tile_(\d\d\d)\s+\{!) {
		print OUT "/Tile_$1 { % $gamelist{$1 + 0}\n";
	}
	else {
		print OUT $_;
	}	
}
close GENTL;

